version: '3.6'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: always
    hostname: gl1.$DEMO_HOSTNAME
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gl1.$DEMO_HOSTNAME'
        gitlab_rails['gitlab_shell_ssh_port'] = 2255
        letsencrypt['enable'] = true
        letsencrypt['contact_emails'] = ['me@$DEMO_HOSTNAME']
        mattermost_external_url 'https://mm1.$DEMO_HOSTNAME'
        mattermost['env'] = {'MM_FEATUREFLAGS_AppsEnabled' => "true"}
        nginx['custom_nginx_config'] = "include /nginx/*.conf;"
    ports:
      - '80:80'
      - '443:443'
      - '2255:22'
    volumes:
      - '/home/ubuntu/osc-workshop-2022/gitlab/config:/etc/gitlab'
      - '/home/ubuntu/osc-workshop-2022/gitlab/logs:/var/log/gitlab'
      - '/home/ubuntu/osc-workshop-2022/gitlab/data:/var/opt/gitlab'
      - '/home/ubuntu/osc-workshop-2022/gitlab/nginx:/nginx'
    shm_size: '256m'
  healthchecks:
    image: lscr.io/linuxserver/healthchecks
    container_name: healthchecks
    environment:
      - PUID=1000
      - PGID=1000
      - SITE_ROOT=https://hc1.$DEMO_HOSTNAME
      - SITE_NAME=Healthchecks
      - DEFAULT_FROM_EMAIL=me@$DEMO_HOSTNAME
      - EMAIL_HOST=$DEMO_HOSTNAME
      - EMAIL_PORT=25
      - EMAIL_HOST_USER=andrew
      - EMAIL_HOST_PASSWORD=argonaut
      - EMAIL_USE_TLS=False
      - SUPERUSER_EMAIL=me@$DEMO_HOSTNAME
      - SUPERUSER_PASSWORD=argonaut
    volumes:
      - '/home/ubuntu/osc-workshop-2022/healthchecks:/config'
    ports:
      - 8000:8000
    restart: always
  deckofcards:
    container_name: deckofcards
    build: ./deckofcards
    restart: always
    ports:
      - '8005:8005'
    volumes:
      - '/home/ubuntu/osc-workshop-2022/deckofcards:/src'
    shm_size: '256m'
